/**
 * DBZ Legends - Export Symbols Script
 * 
 * This script exports symbols from Ghidra in a format compatible with
 * the DBZ Legends decompilation project build system.
 * 
 * @author DBZ Legends Decompilation Team
 * @category DBZ
 */

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Program;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolTable;
import ghidra.program.model.symbol.SymbolIterator;
import ghidra.program.model.symbol.SourceType;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class ExportSymbols extends GhidraScript {
    
    @Override
    public void run() throws Exception {
        println("=== DBZ Legends Symbol Export Script ===");
        
        Program program = getCurrentProgram();
        if (program == null) {
            printerr("No program is currently open!");
            return;
        }
        
        // Ask user for output file
        File outputFile = askFile("Export Symbols", "Save symbols to file");
        if (outputFile == null) {
            println("Export cancelled.");
            return;
        }
        
        // Ask for overlay name
        String overlayName = askString("Overlay Name", 
            "Enter overlay name (main, game, title, etc.):", "main");
        if (overlayName == null || overlayName.trim().isEmpty()) {
            overlayName = "main";
        }
        
        // Export symbols
        exportSymbols(program, outputFile, overlayName);
        
        println("Symbol export completed: " + outputFile.getAbsolutePath());
    }
    
    /**
     * Export symbols to a file in project format
     */
    private void exportSymbols(Program program, File outputFile, String overlayName) throws IOException {
        SymbolTable symbolTable = program.getSymbolTable();
        List<SymbolInfo> symbols = new ArrayList<>();
        
        // Collect all user-defined symbols
        SymbolIterator iter = symbolTable.getAllSymbols(true);
        while (iter.hasNext()) {
            Symbol symbol = iter.next();
            
            // Skip default symbols and external symbols
            if (symbol.getSource() == SourceType.USER_DEFINED ||
                symbol.getSource() == SourceType.ANALYSIS) {
                
                String name = symbol.getName();
                Address address = symbol.getAddress();
                
                // Skip default function names
                if (!name.startsWith("FUN_") && !name.startsWith("DAT_") && 
                    !name.startsWith("LAB_") && !name.startsWith("UNK_")) {
                    
                    symbols.add(new SymbolInfo(name, address.getOffset(), 
                                             symbol.getSymbolType().toString()));
                }
            }
        }
        
        // Sort symbols by address
        Collections.sort(symbols, new Comparator<SymbolInfo>() {
            @Override
            public int compare(SymbolInfo a, SymbolInfo b) {
                return Long.compare(a.address, b.address);
            }
        });
        
        // Write to file
        try (FileWriter writer = new FileWriter(outputFile)) {
            writer.write("# DBZ Legends - " + overlayName + " overlay symbols\n");
            writer.write("# Generated by Ghidra ExportSymbols script\n");
            writer.write("# Format: address name type\n\n");
            
            for (SymbolInfo symbol : symbols) {
                writer.write(String.format("0x%08X %s %s\n", 
                    symbol.address, symbol.name, symbol.type));
            }
            
            writer.write("\n# Total symbols exported: " + symbols.size() + "\n");
        }
        
        println("Exported " + symbols.size() + " symbols for overlay: " + overlayName);
    }
    
    /**
     * Helper class to store symbol information
     */
    private static class SymbolInfo {
        public final String name;
        public final long address;
        public final String type;
        
        public SymbolInfo(String name, long address, String type) {
            this.name = name;
            this.address = address;
            this.type = type;
        }
    }
}