<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PsxTools2\PsxToolsWinforms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\FACE_B_Control.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\EFF_AUTO_B_Control.cs" />
    <Compile Update="Controls\STG_TX_Control.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\LOAD_B_Control.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>