#!/usr/bin/env python3
"""
DBZ Legends - symbols.py
Symbol management utility
"""

import argparse
import os
import re
import sys


def load_symbols(filepath):
    """Load symbols from a file."""
    symbols = {}
    if not os.path.exists(filepath):
        return symbols
    
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            # Parse: name = address; [// comment]
            match = re.match(r'(\w+)\s*=\s*(0x[0-9A-Fa-f]+)\s*;', line)
            if match:
                name, addr = match.groups()
                symbols[name] = int(addr, 16)
    
    return symbols


def save_symbols(filepath, symbols):
    """Save symbols to a file."""
    with open(filepath, 'w') as f:
        f.write(f"# DBZ Legends symbols\n")
        f.write(f"# Auto-generated by symbols.py\n\n")
        
        for name, addr in sorted(symbols.items(), key=lambda x: x[1]):
            f.write(f"{name} = 0x{addr:08X};\n")


def add_symbol(filepath, name, address):
    """Add or update a symbol."""
    symbols = load_symbols(filepath)
    symbols[name] = address
    save_symbols(filepath, symbols)
    print(f"Added/updated symbol: {name} = 0x{address:08X}")


def find_symbol(filepath, pattern):
    """Find symbols matching a pattern."""
    symbols = load_symbols(filepath)
    regex = re.compile(pattern, re.IGNORECASE)
    
    for name, addr in sorted(symbols.items(), key=lambda x: x[1]):
        if regex.search(name):
            print(f"{name} = 0x{addr:08X}")


def list_symbols(filepath):
    """List all symbols."""
    symbols = load_symbols(filepath)
    
    for name, addr in sorted(symbols.items(), key=lambda x: x[1]):
        print(f"{name} = 0x{addr:08X}")


def main():
    parser = argparse.ArgumentParser(description="Symbol management utility")
    subparsers = parser.add_subparsers(dest='command')
    
    # Add command
    add_parser = subparsers.add_parser('add', help='Add a symbol')
    add_parser.add_argument('file', help='Symbol file')
    add_parser.add_argument('name', help='Symbol name')
    add_parser.add_argument('address', help='Symbol address (hex)')
    
    # Find command
    find_parser = subparsers.add_parser('find', help='Find symbols')
    find_parser.add_argument('file', help='Symbol file')
    find_parser.add_argument('pattern', help='Search pattern (regex)')
    
    # List command
    list_parser = subparsers.add_parser('list', help='List all symbols')
    list_parser.add_argument('file', help='Symbol file')
    
    args = parser.parse_args()
    
    if args.command == 'add':
        addr = int(args.address, 16) if args.address.startswith('0x') else int(args.address)
        add_symbol(args.file, args.name, addr)
    elif args.command == 'find':
        find_symbol(args.file, args.pattern)
    elif args.command == 'list':
        list_symbols(args.file)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
